apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: itlj6p7ia-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: itlj6p7ia-go 
  name: itlj6p7ia-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: itlj6p7ia-go 
